@echo off
title Iniciando a API.
echo .............................................................
echo ................. A Tela vai iniciar ........................
echo .............................................................
echo
env\Scripts\activate && python Main/startapp.py runserver --host 127.0.0.1 --port 5000