@echo off
title Iniciando a API.
echo .............................................................
echo ................. A Tela vai iniciar ........................
echo .............................................................
echo
cd Front-React/ui-react && yarn start